### ISSUE TITLE
Dydnd on wear 3.0

### ISSUE THREAD

**Issue by kaiontour** [rkkr/wear-dnd-sync#2]
Hallo, i have a Galaxy watch4 classic which is running wear OS 3.

When i' install the application on my watch i i don't see it in Launcher. 

When I look for permissions I don't see the app either.

Where is at work on wear OS 3?

Thx kai

**Comment by rkkr** [comment]
Instructions are in: https://github.com/rkkr/wear-dnd-sync#setup .

There's no UI in Watch application. I haven't tested if this app still works in Wear 3 as I don't have a Wear 3 watch.

**Comment by kaiontour** [comment]
I did it all. It seems that the permissions cannot be set. See logs

Phone logs:
App version 50:
--------- beginning of system
12-03 09:21:08.045 20294 20294 I Timeline: Timeline: Activity_launch_request time:356540800
12-03 09:57:55.728 20294 20294 I Timeline: Timeline: Activity_launch_request time:358490930
12-03 09:58:09.703 20294 20294 I Timeline: Timeline: Activity_launch_request time:358504905
12-03 10:04:02.865 20294 20294 I Timeline: Timeline: Activity_launch_request time:358858067
12-03 20:40:07.609 26449 26449 I Timeline: Timeline: Activity_launch_request time:375518304
--------- beginning of main
12-03 20:45:21.419 26449 28329 D SettingsService: onMessageReceived: MessageEventParcelable[16804,/dnd_register, size=37]
12-03 20:45:21.420 26449 28329 D SettingsService: Connected broadcast
12-03 20:45:21.420 26449 26449 D MainActivity: Callback to UI: rkr.weardndsync.WEAR_CALLBACK_CONNECT
12-03 20:45:21.420 26449 26449 W MainActivity: Watch DND permission not granted
12-03 20:45:21.420 26449 26449 W MainActivity: Watch DND permission not granted
12-03 20:45:26.557 26449 26449 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
Watch logs:
App version 50:
--------- beginning of main
12-03 20:42:57.356 14288 14288 E rkr.weardndsyn: Not starting debugger since process cannot load the jdwp agent.
12-03 20:42:57.420 14288 14288 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
12-03 20:42:57.477 14288 14288 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-03 20:42:57.482 14288 14288 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-03 20:42:57.561 14288 14306 D SettingsService: onMessageReceived: MessageEventParcelable[16601,/dnd_switch, size=43]
12-03 20:43:47.896 14288 14321 D SettingsService: onMessageReceived: MessageEventParcelable[16602,/dnd_register, size=0]
12-03 20:45:21.166 14288 14369 D SettingsService: onMessageReceived: MessageEventParcelable[16603,/dnd_register, size=0]
12-03 20:45:27.136 14288 14372 D SettingsService: onMessageReceived: MessageEventParcelable[16604,/dnd_logs, size=0]


⁣

**Comment by rkkr** [comment]
Congrads, your watch does not support Notification Service.
